### ISSUE TITLE
expected value after metric, got "\n" ("INVALID") while parsing: "nvidiasmi_power_state_int

### ISSUE THREAD

**Issue by coolham123** [e7d/docker-prometheus-nvidiasmi#1]
Hello - Getting the following error in the prometheus targets page:

`expected value after metric, got "\n" ("INVALID") while parsing: "nvidiasmi_power_state_int{id=\"00000000:01:00.0\",uuid=\"GPU-xxxxxxxxxxxxxxxxx\",name=\"Tesla P40\"} \n"`

and from the /metrics page

`nvidiasmi_power_state_int{id="00000000:03:00.0",uuid="xxxxxxxxxx",name="Tesla P40"} `

Running Nvidia Driver 535.54.03

System is unraid.

**Comment by blub3k** [comment]
should be fixed with https://github.com/e7d/docker-prometheus-nvidiasmi/pull/2
waiting for pull request to be merged

**Comment by e7d** [comment]
Hello @coolham123 and @blub3k,

As said on the PR https://github.com/e7d/docker-prometheus-nvidiasmi/pull/2, I'll try to review and test this today.
If it works as expected, I'll merge it and rebuild the container.

Regards.

**Comment by e7d** [comment]
Hello @coolham123 

https://github.com/e7d/docker-prometheus-nvidiasmi/pull/3 should have resolved your issue.
The docker image is also up-to-date, but now splitted in two tags, depending if you are using a CUDA 11 or CUDA 12 base platform.

Regards.

**Comment by ich777** [comment]
Thank you!
